sudo: required
language: go
go:
  - "1.11.x"
services:
  - docker
stages:
  - test
git:
  submodules: false
  quiet: false
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: test
      script:
        - make example
    - stage: test
      script:
        - make coverage