sudo: required
language: go
go:
  - "1.12.x"
services:
  - docker
stages:
  - test
git:
  submodules: false
  quiet: false
env:
  - GO111MODULE=on
jobs:
  include:
    - stage: test
      env:
        - TYPE=example
      script:
        - make example
    - stage: test
      env:
        - TYPE=integration
      script:
        - docker pull fluent/fluentd:v1.5-1
        - make test_integration
    - stage: test
      env:
        - TYPE=unit
      script:
        - make test_unit